### ISSUE TITLE
This error

### ISSUE THREAD

**Issue by 55MegaCanon** [deluvsushi/13MINXMZZB0V2#3]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/13MINXMZZB0V2/13MINXMZZB0V2.py", line 2, in <module>
    from pyfiglet import figlet__format
ImportError: cannot import name 'figlet__format' from 'pyfiglet' (/data/data/com.termux/files/usr/lib/python3.10/site-packages/pyfiglet/__init__.py)

**Comment by deluvsushi** [comment]
reinstall script

**Comment by 55MegaCanon** [comment]
> reinstall script

How?
